
services:
  postgres:
    image: postgres:16-trixie
    container_name: sql-study-postgres
    environment:
      POSTGRES_USER: study_user
      POSTGRES_PASSWORD: study_password
      POSTGRES_DB: study_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U study_user -d study_db"]
      interval: 10s
      timeout: 5s
      retries: 5

